spring:
  datasource:
    password: sessionvote123
    username: root
    url: 'jdbc:google:mysql://session-vote:southamerica-east1:session-vote/pauta'
    driver-class-name: com.mysql.jdbc.GoogleDriver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080